"""
Airco Insights — HDFC Parser (Accuracy-First)
==============================================
Extracts transactions from HDFC Bank PDF statements with 100% row capture.

HDFC Statement Format:
- Columns: Date | Narration | Chq./Ref.No. | Value Dt | Withdrawal Amt. | Deposit Amt. | Closing Balance
- Date format: DD/MM/YY or DD/MM/YYYY
- Amounts in Indian format: 1,03,766.81
- Multi-line narrations wrapped across lines
- No spaces between words in narration (HDFC PDF quirk)

Strategy:
1. Parse using pdfplumber tables first (most accurate)
2. Fall back to text-based parsing if tables fail
3. Track balance continuity to determine debit vs credit
4. Validate every extracted row

Design: Extract ALL transactions or fail. No partial extraction.
"""

import logging
import re
from typing import List, Dict, Any, Optional, Tuple
from dataclasses import dataclass, field
from datetime import datetime

logger = logging.getLogger(__name__)


class HDFCParseError(Exception):
    """Raised when HDFC parsing fails."""
    def __init__(self, message: str, error_code: str, details: dict = None):
        self.error_code = error_code
        self.details = details or {}
        super().__init__(message)


@dataclass
class HDFCTransaction:
    """Single HDFC transaction."""
    date: str
    description: str
    debit: Optional[float]
    credit: Optional[float]
    balance: float
    ref_no: str = ""
    value_date: str = ""
    raw_line: str = ""
    line_number: int = 0
    
    def to_dict(self) -> dict:
        return {
            "date": self.date,
            "description": self.description,
            "debit": self.debit,
            "credit": self.credit,
            "balance": self.balance,
            "ref_no": self.ref_no,
            "value_date": self.value_date,
        }


@dataclass
class HDFCParseResult:
    """Result of HDFC parsing."""
    transactions: List[HDFCTransaction]
    total_count: int
    parse_method: str  # "table" or "text"
    opening_balance: Optional[float] = None
    closing_balance: Optional[float] = None
    total_credits: float = 0.0
    total_debits: float = 0.0
    warnings: List[str] = field(default_factory=list)
    
    def to_dict(self) -> dict:
        return {
            "total_count": self.total_count,
            "parse_method": self.parse_method,
            "opening_balance": self.opening_balance,
            "closing_balance": self.closing_balance,
            "total_credits": self.total_credits,
            "total_debits": self.total_debits,
            "warnings": self.warnings,
        }


class HDFCParser:
    """
    Accuracy-first HDFC Bank statement parser.
    """
    
    # Date pattern: DD/MM/YY or DD/MM/YYYY
    DATE_RE = re.compile(r'^(\d{2}/\d{2}/\d{2,4})\s*')
    
    # Amount pattern: Indian format 1,03,766.81
    AMOUNT_RE = re.compile(r'(\d[\d,]*\.\d{2})')
    
    # Header/footer patterns to skip
    SKIP_PATTERNS = [
        "HDFCBANKLIMITED", "HDFC BANK LIMITED", "Statementofaccount",
        "Statement of account", "PageNo", "Page No", "AccountBranch",
        "Account Branch", "StatementFrom", "Statement From",
        "Closingbalanceinclude", "Contents of this statement",
        "Contentsofthisstatement", "StateaccountbranchGSTN",
        "RegisteredOfficeAddress", "HDFCBankGSTIN", "www.hdfcbank.com",
        "Date Narration", "DateNarration", "Chq./Ref.No", "WithdrawalAmt",
        "DepositAmt", "ClosingBalance", "AccountNo", "AccountStatus",
        "JOINTHOLDERS", "BranchCode", "ProductCode", "Nomination",
        "CustID", "ODLimit", "Currency", "Phoneno", "Email",
        "RTGS/NEFTIFSC", "A/COpenDate", "STATEMENTSUMMARY",
        "Statement Summary", "OpeningBalance", "Opening Balance",
        "DrCount", "CrCount", "ClosingBal", "Thisisacomputergenerated",
        "This is a computer generated", "notrequiresignature",
        "does not require signature", "GeneratedOn", "Generated On",
        "GeneratedBy", "Generated By", "RequestingBranchCode",
        "Requesting Branch Code", "AccountType", "Account Type",
        "Address :", "City :", "State :", "GROUNDFLR", "SECTOR17", "MICR:",
    ]
    
    # Pure amounts line pattern
    PURE_AMOUNTS_RE = re.compile(r'^[\d,\.\s]+$')
    
    def __init__(self):
        self.logger = logging.getLogger(f"{__name__}.{self.__class__.__name__}")
    
    def parse(self, file_path: str, text_content: str = "") -> HDFCParseResult:
        """
        Parse HDFC statement and extract all transactions.
        
        Args:
            file_path: Path to PDF file
            text_content: Pre-extracted text content (optional)
            
        Returns:
            HDFCParseResult with all transactions
            
        Raises:
            HDFCParseError: If parsing fails
        """
        self.logger.info("Parsing HDFC statement: %s", file_path)

        # Detect scanned/image-only PDFs early
        if self._is_image_only_pdf(file_path):
            raise HDFCParseError(
                "This PDF appears to be a scanned image and cannot be processed. "
                "Please upload a text-based PDF downloaded directly from HDFC Bank's internet banking portal.",
                error_code="SCANNED_PDF",
                details={"file": file_path}
            )

        # Try table-based parsing first (most accurate)
        try:
            result = self._parse_with_tables(file_path)
            if result.total_count > 0:
                self.logger.info("Table parsing succeeded: %d transactions", result.total_count)
                return result
        except Exception as e:
            self.logger.warning("Table parsing failed: %s, falling back to text", str(e))
        
        # Fall back to text-based parsing
        if not text_content:
            text_content = self._extract_text(file_path)
        
        result = self._parse_with_text(text_content)
        
        if result.total_count == 0:
            raise HDFCParseError(
                "No transactions extracted from HDFC statement",
                error_code="NO_TRANSACTIONS",
                details={"file": file_path}
            )
        
        self.logger.info("Text parsing succeeded: %d transactions", result.total_count)
        return result
    
    def _is_image_only_pdf(self, file_path: str) -> bool:
        """Return True if the PDF has no extractable text (scanned image)."""
        try:
            import pdfplumber
            with pdfplumber.open(file_path) as pdf:
                pages_to_check = min(3, len(pdf.pages))
                for page in pdf.pages[:pages_to_check]:
                    words = page.extract_words()
                    if words:
                        return False
            return True
        except Exception:
            return False

    def _extract_text(self, file_path: str) -> str:
        """Extract text from PDF using pdfplumber."""
        try:
            import pdfplumber
            pages = []
            with pdfplumber.open(file_path) as pdf:
                for page in pdf.pages:
                    text = page.extract_text() or ""
                    pages.append(text)
            return "\n".join(pages)
        except Exception as e:
            raise HDFCParseError(
                f"Failed to extract text from PDF: {str(e)}",
                error_code="TEXT_EXTRACTION_FAILED",
                details={"error": str(e)}
            )
    
    # ====================================================================
    # COORDINATE-BASED COLUMN BOUNDARIES (from PDF word-position analysis)
    # ====================================================================
    _COL_DATE_MAX = 65       # Date column: x < 65
    _COL_NARR_MAX = 260      # Narration: 65 <= x < 260
    _COL_REF_MAX = 360       # Chq./Ref.No: 260 <= x < 360
    _COL_VDT_MAX = 405       # Value Date: 360 <= x < 405
    _COL_WDR_MAX = 485       # Withdrawal: 405 <= x < 485
    _COL_DEP_MAX = 562       # Deposit: 485 <= x < 562
                              # Balance: x >= 562
    _DATA_Y_MIN = 230        # Skip page headers (address block)
    _DATA_Y_MAX = 790        # Skip page footers
    _DATE_EXACT_RE = re.compile(r'^\d{2}/\d{2}/\d{2}$')
    
    @staticmethod
    def _get_column(x0: float) -> str:
        """Assign a word to its column based on x-coordinate."""
        if x0 < HDFCParser._COL_DATE_MAX:
            return 'date'
        elif x0 < HDFCParser._COL_NARR_MAX:
            return 'narration'
        elif x0 < HDFCParser._COL_REF_MAX:
            return 'ref_no'
        elif x0 < HDFCParser._COL_VDT_MAX:
            return 'value_date'
        elif x0 < HDFCParser._COL_WDR_MAX:
            return 'withdrawal'
        elif x0 < HDFCParser._COL_DEP_MAX:
            return 'deposit'
        else:
            return 'balance'
    
    def _extract_page_lines(self, page) -> list:
        """Extract words from a PDF page, group by y into lines, assign to columns."""
        from collections import defaultdict
        
        words = page.extract_words(keep_blank_chars=True, x_tolerance=2, y_tolerance=2)
        if not words:
            return []
        
        # Group words by approximate y-position (within 5 units = same visual line)
        y_groups = defaultdict(list)
        for w in words:
            y_key = round(w['top'] / 5) * 5
            y_groups[y_key].append(w)
        
        lines = []
        for y_key in sorted(y_groups.keys()):
            # Skip lines outside the transaction data area (page headers/footers)
            if y_key < self._DATA_Y_MIN or y_key > self._DATA_Y_MAX:
                continue
            
            line_words = sorted(y_groups[y_key], key=lambda w: w['x0'])
            
            # Build column contents
            col_words = defaultdict(list)
            for w in line_words:
                col = self._get_column(w['x0'])
                col_words[col].append(w['text'])
            
            lines.append({
                'y': y_key,
                'date': ' '.join(col_words.get('date', [])).strip(),
                'narration': ' '.join(col_words.get('narration', [])).strip(),
                'ref_no': ' '.join(col_words.get('ref_no', [])).strip(),
                'value_date': ' '.join(col_words.get('value_date', [])).strip(),
                'withdrawal': ' '.join(col_words.get('withdrawal', [])).strip(),
                'deposit': ' '.join(col_words.get('deposit', [])).strip(),
                'balance': ' '.join(col_words.get('balance', [])).strip(),
            })
        
        return lines
    
    def _parse_with_tables(self, file_path: str) -> HDFCParseResult:
        """
        Parse HDFC PDF using COORDINATE-BASED column detection.
        
        This method uses word x-coordinates from pdfplumber to assign each
        word to the correct column, eliminating multi-line cell alignment
        issues that plague table-based extraction.
        
        STRATEGY:
        1. Extract words with x,y positions from each page
        2. Group by y-position into visual lines
        3. Assign words to columns by x-coordinate boundaries
        4. Transaction start = valid DD/MM/YY in Date col + valid amount in Balance col
        5. Continuation = narration/ref content without date → append to previous txn
        6. Balance continuity determines withdrawal vs deposit (mathematically correct)
        """
        import pdfplumber
        
        transactions = []
        prev_balance = None
        
        with pdfplumber.open(file_path) as pdf:
            for page_num, page in enumerate(pdf.pages):
                lines = self._extract_page_lines(page)
                
                for line in lines:
                    date_text = line['date']
                    balance_text = line['balance']
                    
                    # Check if this is a transaction start line
                    is_date = bool(self._DATE_EXACT_RE.match(date_text))
                    balance_val = self._clean_amount(balance_text) if balance_text else None
                    
                    if is_date and balance_val is not None:
                        # === NEW TRANSACTION ===
                        withdrawal_val = self._clean_amount(line['withdrawal'])
                        deposit_val = self._clean_amount(line['deposit'])
                        vdt = line['value_date']
                        value_date = vdt if self._DATE_EXACT_RE.match(vdt) else date_text
                        
                        # Determine debit/credit from balance movement
                        if prev_balance is not None:
                            balance_change = balance_val - prev_balance
                            if balance_change < -0.005:
                                # Balance decreased → WITHDRAWAL
                                if not withdrawal_val:
                                    withdrawal_val = round(abs(balance_change), 2)
                                deposit_val = None
                            elif balance_change > 0.005:
                                # Balance increased → DEPOSIT
                                if not deposit_val:
                                    deposit_val = round(balance_change, 2)
                                withdrawal_val = None
                            else:
                                withdrawal_val = None
                                deposit_val = None
                        else:
                            # First transaction — use whatever column has data
                            if deposit_val and not withdrawal_val:
                                pass
                            elif withdrawal_val and not deposit_val:
                                pass
                            elif deposit_val and withdrawal_val:
                                deposit_val = deposit_val
                                withdrawal_val = None
                        
                        txn = HDFCTransaction(
                            date=date_text,
                            description=line['narration'],
                            debit=withdrawal_val,
                            credit=deposit_val,
                            balance=balance_val,
                            ref_no=line['ref_no'],
                            value_date=value_date,
                        )
                        transactions.append(txn)
                        prev_balance = balance_val
                    
                    elif transactions:
                        # === CONTINUATION LINE ===
                        # Append narration content to previous transaction
                        if line['narration']:
                            transactions[-1].description += ' ' + line['narration']
                        if line['ref_no'] and not transactions[-1].ref_no:
                            transactions[-1].ref_no = line['ref_no']
        
        # Normalize whitespace in all narrations
        for txn in transactions:
            txn.description = ' '.join(txn.description.split())
        
        self.logger.info(
            "Parsed %d transactions using coordinate-based method", len(transactions)
        )
        
        # Calculate totals
        total_credits = sum(t.credit or 0 for t in transactions)
        total_debits = sum(t.debit or 0 for t in transactions)
        
        opening = transactions[0].balance if transactions else None
        closing = transactions[-1].balance if transactions else None
        
        # Infer opening balance from first transaction
        if transactions:
            first_txn = transactions[0]
            if first_txn.credit:
                opening = first_txn.balance - first_txn.credit
            elif first_txn.debit:
                opening = first_txn.balance + first_txn.debit
        
        return HDFCParseResult(
            transactions=transactions,
            total_count=len(transactions),
            parse_method="coordinate",
            opening_balance=opening,
            closing_balance=closing,
            total_credits=total_credits,
            total_debits=total_debits,
        )
    
    def _parse_table_row(
        self,
        row: List[Any],
        prev_balance: Optional[float],
        page_num: int
    ) -> Optional[HDFCTransaction]:
        """
        Parse a single table row into a transaction.
        
        HDFC columns: Date | Narration | Ref | Value Date | Withdrawal | Deposit | Balance
        
        CRITICAL LOGIC (100% Accurate):
        1. Extract amounts from Withdrawal and Deposit columns
        2. Use BALANCE COMPARISON to validate/determine transaction type:
           - If balance INCREASED from previous → CREDIT
           - If balance DECREASED from previous → DEBIT
        3. This is mathematically correct and catches all edge cases
        """
        try:
            # Extract all columns
            date = str(row[0] or "").strip()
            narration = str(row[1] or "").strip() if len(row) > 1 else ""
            ref_no = str(row[2] or "").strip() if len(row) > 2 else ""
            value_date = str(row[3] or "").strip() if len(row) > 3 else ""
            
            # Extract amount columns directly by position
            withdrawal_str = str(row[4] or "").strip() if len(row) > 4 else ""
            deposit_str = str(row[5] or "").strip() if len(row) > 5 else ""
            balance_str = str(row[6] or "").strip() if len(row) > 6 else ""
            
            # Clean amounts
            withdrawal_amt = self._clean_amount(withdrawal_str)
            deposit_amt = self._clean_amount(deposit_str)
            balance = self._clean_amount(balance_str)
            
            # Must have balance
            if balance is None:
                return None
            
            # Must have either withdrawal or deposit amount
            if withdrawal_amt is None and deposit_amt is None:
                return None
            
            # Determine debit/credit using BALANCE COMPARISON (most accurate)
            debit = None
            credit = None
            
            if prev_balance is not None:
                # Mathematical validation: compare balance change
                if balance > prev_balance:
                    # Balance increased = CREDIT transaction
                    credit = deposit_amt if deposit_amt else (balance - prev_balance)
                elif balance < prev_balance:
                    # Balance decreased = DEBIT transaction
                    debit = withdrawal_amt if withdrawal_amt else (prev_balance - balance)
                else:
                    # Balance unchanged (rare) - trust column values
                    debit = withdrawal_amt
                    credit = deposit_amt
            else:
                # First transaction - use column values directly
                debit = withdrawal_amt
                credit = deposit_amt
            
            return HDFCTransaction(
                date=date,
                description=narration,
                debit=debit,
                credit=credit,
                balance=balance,
                ref_no=ref_no,
                value_date=value_date,
            )
        except Exception as e:
            self.logger.debug("Failed to parse table row: %s", str(e))
            return None
    
    def _parse_with_text(self, text_content: str) -> HDFCParseResult:
        """Parse using text-based extraction."""
        lines = text_content.split("\n")
        raw_entries = []
        current_entry = None
        
        for line_num, line in enumerate(lines):
            stripped = line.strip()
            if not stripped:
                continue
            
            if self._should_skip_line(stripped):
                continue
            
            # Check if line starts with a date
            date_match = self.DATE_RE.match(stripped)
            if date_match:
                date_str = date_match.group(1)
                rest = stripped[date_match.end():].strip()
                
                # Extract amounts
                amounts = self._extract_amounts(rest)
                
                if len(amounts) >= 2:
                    # Save previous entry
                    if current_entry:
                        raw_entries.append(current_entry)
                    
                    # Find narration part
                    amount_positions = list(self.AMOUNT_RE.finditer(rest))
                    if amount_positions:
                        first_pos = amount_positions[0].start()
                        narration_part = rest[:first_pos].strip()
                    else:
                        narration_part = rest
                    
                    current_entry = {
                        "date": date_str,
                        "narration_parts": [narration_part] if narration_part else [],
                        "amounts": amounts,
                        "line_number": line_num,
                    }
                elif len(amounts) == 1:
                    # Continuation line
                    if current_entry:
                        current_entry["narration_parts"].append(stripped)
                else:
                    # Date line without amounts
                    if current_entry:
                        raw_entries.append(current_entry)
                    
                    current_entry = {
                        "date": date_str,
                        "narration_parts": [rest] if rest else [],
                        "amounts": [],
                        "line_number": line_num,
                    }
            else:
                # Continuation line
                if current_entry:
                    amounts = self._extract_amounts(stripped)
                    if amounts and not current_entry["amounts"]:
                        # This continuation has amounts
                        amount_positions = list(self.AMOUNT_RE.finditer(stripped))
                        if amount_positions:
                            first_pos = amount_positions[0].start()
                            narration_part = stripped[:first_pos].strip()
                            if narration_part:
                                current_entry["narration_parts"].append(narration_part)
                        current_entry["amounts"] = amounts
                    else:
                        current_entry["narration_parts"].append(stripped)
        
        # Don't forget last entry
        if current_entry:
            raw_entries.append(current_entry)
        
        # Convert to transactions
        transactions = []
        prev_balance = None
        
        for entry in raw_entries:
            amounts = entry["amounts"]
            if len(amounts) < 2:
                continue
            
            balance = amounts[-1]
            txn_amount = amounts[-2]
            
            # Clean narration
            narration = " ".join(entry["narration_parts"]).strip()
            narration = self._clean_narration(narration)
            
            # Extract ref number
            ref_match = re.search(r'\b(\d{10,})\b', narration)
            ref_no = ref_match.group(1) if ref_match else ""
            
            # Determine debit vs credit
            debit = None
            credit = None
            
            if prev_balance is not None:
                if balance > prev_balance:
                    credit = txn_amount
                elif balance < prev_balance:
                    debit = txn_amount
                else:
                    debit = txn_amount
            else:
                narration_upper = narration.upper()
                if any(kw in narration_upper for kw in ["NEFTCR", "SALARY", "CREDIT", "INT.PD", "INTEREST", "_W2A_CREDIT", "PAYZAPP_W2A"]):
                    credit = txn_amount
                elif balance == txn_amount:
                    credit = txn_amount
                elif balance < txn_amount:
                    debit = txn_amount
                else:
                    credit = txn_amount
            
            prev_balance = balance
            
            transactions.append(HDFCTransaction(
                date=entry["date"],
                description=narration,
                debit=debit,
                credit=credit,
                balance=balance,
                ref_no=ref_no,
                line_number=entry.get("line_number", 0),
            ))
        
        # Calculate totals
        total_credits = sum(t.credit or 0 for t in transactions)
        total_debits = sum(t.debit or 0 for t in transactions)
        
        opening = None
        closing = transactions[-1].balance if transactions else None
        
        if transactions:
            first_txn = transactions[0]
            if first_txn.credit:
                opening = first_txn.balance - first_txn.credit
            elif first_txn.debit:
                opening = first_txn.balance + first_txn.debit
        
        return HDFCParseResult(
            transactions=transactions,
            total_count=len(transactions),
            parse_method="text",
            opening_balance=opening,
            closing_balance=closing,
            total_credits=total_credits,
            total_debits=total_debits,
        )
    
    def _should_skip_line(self, line: str) -> bool:
        """Check if line is header/footer/metadata."""
        upper = line.upper()
        for pattern in self.SKIP_PATTERNS:
            if pattern.upper() in upper:
                return True
        
        # Skip pure amounts lines
        if self.PURE_AMOUNTS_RE.match(line) and len(line) > 10:
            return True
        
        return False
    
    def _extract_amounts(self, text: str) -> List[float]:
        """Extract all Indian-format amounts from text."""
        matches = self.AMOUNT_RE.findall(text)
        amounts = []
        for m in matches:
            val = self._clean_amount(m)
            if val is not None:
                amounts.append(val)
        return amounts
    
    def _clean_amount(self, val: str) -> Optional[float]:
        """Convert Indian-format amount to float."""
        if not val or not val.strip():
            return None
        cleaned = val.strip().replace(",", "")
        try:
            return float(cleaned)
        except (ValueError, TypeError):
            return None
    
    def _clean_narration(self, narration: str) -> str:
        """Clean up narration text."""
        # Remove leaked footer fragments
        narration = re.sub(
            r'\s*(thisstatement\.|Thisisacomputer.*|notrequiresignature.*|'
            r'Contentsofthisstatement.*|Closingbalanceinclude.*|'
            r'StateaccountbranchGSTN.*|RegisteredOfficeAddress.*|'
            r'HDFCBankGSTIN.*|www\.hdfcbank\.com.*)$',
            '', narration, flags=re.IGNORECASE
        ).strip()
        return narration
